name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: make build

      - name: Test
        env:
          TEST_DSN: ${{ secrets.TEST_DSN }}
        run: go test -v -tags integration -race ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate third party files
        run: make swagger-ui
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39